### ISSUE TITLE
This and the Gateway

### ISSUE THREAD

**Issue by garudaonekh** [thingsboard/thingsboard-python-client-sdk#9]
Indecisive between this one and the Thingsboard gateway. 
I am new two both of this. 
Currently, I have a control software(Raspberry PI) which read data from all sensors and stored in InfluxDB and also manage all the output relays. I want to push all these info to my Thingsboard cloud. I am not sure which is a good options.

Thanks;

**Comment by zbeacon** [comment]
Hi @garudaonekh ,

Thank your for your interest in ThingsBoard Python client SDK. Probably it will be better to use this SDK in your case. Because of it will be more convenient to develop and manage data you need. In case of the gateway - it allows to collect and send data, but I see only variant with using ODBC connector and driver for connection to InfluxDB. It will be more difficult (By my personal opinion). Whenever you can use the both instruments and reach your goal.

**Comment by garudaonekh** [comment]
Thanks, anyhow I go for Thingsboard Gateway. I push all the data to local MQTT and let the Thingsboard Gateway push it to Thingsboard Cloud. It's a bit duplicate of work.
